WpfMath/XmlUtilities.cs
=> Culture invariant parsing in XmlUtilities

WpfMath/SymbolAtom.cs, WpfMath/TexFormulaParser.cs
Fixes #25 
We need to investigate occurences of "GetSmth + exception" methods later.
=> Use TryGet methods instead exception handling

WpfMath.Tests/ParserTests.fs, WpfMath.Tests/Utils.fs, WpfMath.Tests/WpfMath.Tests.fsproj, WpfMath.Tests/packages.config, WpfMath/TexFormulaParser.cs
=> TexFormulaParser: Propagate text style through parsing

WpfMath/Data/PredefinedTexFormulas.xml
Just trying \mathrm for new math commands...
=> Add \lim command

LICENSE.md, README.md, RELEASES.md, WpfMath.nuspec, src/WpfMath.Example/Properties/AssemblyInfo.cs, src/WpfMath.Tests/AssemblyInfo.fs, src/WpfMath/Properties/AssemblyInfo.cs
Hope this is alright. Let me know if you have any complaints!
=> Improved text and style of README, LICENSE, and RELEASES files.

RELEASES.md, WpfMath.nuspec, src/WpfMath.Example/Properties/AssemblyInfo.cs, src/WpfMath.Tests/AssemblyInfo.fs, src/WpfMath/Properties/AssemblyInfo.cs
I suggest we publish a new version today. Any objections?
=> Project: release 0.3.1

src/WpfMath.Example/MainWindow.xaml.cs
When I saved an svg file not everything was written on my computer.
=> force streamwriter to flush buffers

.gitignore, src/WpfMath.Tests/BoxTests.fs, src/WpfMath.Tests/WpfMath.Tests.fsproj, src/WpfMath/AccentedAtom.cs
=> Fix accent alignment

README.md
As discussed in https://github.com/ForNeVeR/wpf-math/issues/110#issuecomment-361077280
=> Add a license info link to the README file

README.md
After solving #118 I got the idea to improve our usage docs.
=> Add new examples into the README file

src/WpfMath/SVGConverter.cs
Small Fix (refactoring). From SVGConverter class has been remove unused variables.
=> removed unused variables

src/WpfMath.Tests/ParserTests.fs, src/WpfMath.Tests/TestResults/ParserTests.textWithExpression.approved.txt
Closes #181.
Everything is okay with this test, so I've just enabled it :)
=> Enable textWithExpression test (#181)

src/WpfMath.Tests/ParserTests.fs, src/WpfMath.Tests/TestResults/ParserTests.commandsInText.approved.txt, src/WpfMath.Tests/TestResults/ParserTests.underscoreText.approved.txt, src/WpfMath/TexFormulaParser.cs
=> Exclude plain text from formula parsing

src/WpfMath/Atoms/Radical.cs, src/WpfMath/Atoms/StyledAtom.cs, src/WpfMath/Rendering/GeometryElementRenderer.cs, src/WpfMath/Rendering/IElementRenderer.cs, src/WpfMath/Rendering/WpfElementRenderer.cs, src/WpfMath/TexRenderer.cs
- Closes #128.
- Closes #146 (I've incorporated the useful code from that PR).
=> Separate layers for the formula background and foreground

src/WpfMath.Tests/BoxTests.fs, src/WpfMath.Tests/TestResults/BoxTests.emptyColorbox.approved.txt, src/WpfMath/Atoms/RowAtom.cs, src/WpfMath/Boxes/StrutBox.cs, src/WpfMath/TexFormula.cs
=> Fix the crashing parser by empty (#203)

src/WpfMath.Tests/ParserExceptionTests.fs, src/WpfMath.Tests/Utils.fs
Closes #176 (which is actually already fixed but we have no tests for that).
=> Add a test for #176

src/WpfMath.Tests/ParserExceptionTests.fs, src/WpfMath.Tests/ParserTests.fs, src/WpfMath.Tests/TestResults/ParserTests.binom.( 2 x123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.( 2(x)123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.((2)(x)123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.((2)x123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.(2 (x)123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.(2(x)123).approved.txt, src/WpfMath.Tests/TestResults/ParserTests.binom.(2x123).approved.txt, src/WpfMath/Parsers/StandardCommands.cs
=> #174 Add binom command

src/WpfMath.Tests/BoxTests.fs, src/WpfMath.Tests/ParserExceptionTests.fs, src/WpfMath.Tests/TestResults/BoxTests.emptyColorRed.approved.txt
=> Add tests for `\color{red}` (#158)

appveyor.yml
=> Update to the release VS2019 image

src/WpfMath.Tests/ParserTests.fs, src/WpfMath.Tests/TestResults/ParserTests.oneNonAsciiSymbolText.approved.txt, src/WpfMath/Atoms/ScriptsAtom.cs
=> Fix throw exception for the non-ascii symbol (#225)

src/WpfMath.Example/MainWindow.xaml, src/WpfMath.Example/MainWindow.xaml.cs
=> add ComboBox into an example application

src/AvaloniaMath.Example/App.xaml, src/AvaloniaMath.Example/AvaloniaMath.Example.csproj, src/AvaloniaMath.Example/Program.cs, src/AvaloniaMath.Example/Views/MainWindow.xaml, src/AvaloniaMath/AvaloniaMath.csproj, src/AvaloniaMath/Controls/FormulaBlock.cs, src/AvaloniaMath/DefaultTexFontParser.cs, src/AvaloniaMath/SystemFont.cs
Upgrade Avalonia version
Resolve
>  make `FormulaBlock` public
in TODO list https://github.com/ForNeVeR/wpf-math/issues/17#issuecomment-453836924
=> Upgrade Avalonia version

src/WpfMath/Utils/Result.cs
Thanks to [Iλya Che in DotNetRuChat](https://t.me/DotNetRuChat/752883) for noticing the issue.
=> Fix parameter order in ArgumentException constructor

src/WpfMath.Tests/ParserExceptionTests.fs, src/WpfMath/TexFormulaParser.cs
=> Fix throws exception by \color

src/WpfMath.Tests/OverUnderBoxTests.fs, src/WpfMath/Boxes/OverUnderBox.cs
=> Fix NRE in OverUnderBox

README.md
=> Fixed the link path

.editorconfig, .github/workflows/main.yml, .github/workflows/nuget.yml, .idea/.idea.WpfMath/.idea/dictionaries/fried.xml, CHANGELOG.md, MAINTAINERSHIP.md, NuGet.Config, README.md, WpfMath.sln, src/WpfMath/WpfMath.csproj
I plan to disable Appveyor for this project (GHA looks more reliable at the moment).
**TODO:**
=> CI: migrate to GitHub Actions

CHANGELOG.md, src/WpfMath.Tests/ParserTests.fs, src/WpfMath.Tests/TestResults/ParserTests.sqrt.(()).approved.txt, src/WpfMath/TexFormulaParser.cs
=> Fix crash on \sqrt{}

Directory.Build.props, WpfMath.sln, src/WpfMath.Example/WpfMath.Example.csproj, src/WpfMath/Properties/AssemblyInfo.cs, src/WpfMath/WpfMath.csproj
Refactor msbuild props. This will make it easier to keep track of the language version and nullability.
=> Refactor msbuild props

src/WpfMath/TexFormula.cs
=> (#304) GetSystemFont: make it work with the localized font names

scripts/verify-encoding.ps1
Actually, I've noted a double space in a comment, but if I'm doing a PR anyway, why not improve other comments a little bit, too.
=> Scripts: small comment updates

README.md
=> (#260) Docs: document the exception thrown

CHANGELOG.md, Directory.Build.props, src/WpfMath.Example/WpfMath.Example.csproj, src/WpfMath.Tests/WpfMath.Tests.fsproj, src/WpfMath/WpfMath.csproj
=> (#350) Pack: remove the package dependency

CHANGELOG.md, src/AvaloniaMath.Example/AvaloniaMath.Example.csproj, src/AvaloniaMath/AvaloniaMath.csproj, src/WpfMath.Example/WpfMath.Example.csproj, src/WpfMath.Tests/WpfMath.Tests.fsproj, src/WpfMath/WpfMath.csproj
Closes #238.
Let's see how CI reacts to this, and publish them next time if it works.
=> Migrate to portable PDB

Directory.Build.props, MAINTAINERSHIP.md, src/AvaloniaMath/AvaloniaMath.csproj, src/WpfMath.Shared/WpfMath.Shared.csproj, src/WpfMath/WpfMath.csproj
=> (#298) Build: collect changelogs automatically

CHANGELOG.md, api/WpfMath.net462.verified.cs, api/WpfMath.net6.0.verified.cs, api/XamlMath.Shared.net462.verified.cs, api/XamlMath.Shared.net6.0.verified.cs, api/XamlMath.Shared.netstandard2.0.verified.cs, src/WpfMath/Rendering/WpfBrush.cs, src/XamlMath.Shared/Colors/StandardColorParsers.cs
=> Minor API cleanup

CHANGELOG.md, Directory.Build.props
=> Release: prepare v1.0.0

.github/workflows/nuget.yml
=> CI: update the XAML-Math Shared Code binary name

Directory.Build.props
=> (#375) Pack: add README

api/WpfMath.net462.verified.cs, api/WpfMath.net6.0.verified.cs
This should fix scheduled test failures.
See #380 for more details.
=> Tests: update to .NET SDK 7.0.203

src/XamlMath.Shared/Atoms/MatrixAtom.cs
=> Improve matrix atom

src/WpfMath.Example/App.xaml, src/WpfMath.Example/App.xaml.cs, src/WpfMath.Example/MainViewModel.cs, src/WpfMath.Example/MainWindow.xaml, src/WpfMath.Example/MainWindow.xaml.cs, src/WpfMath.Example/Preset.cs, src/WpfMath.Example/WpfMath.Example.csproj
I'll be AFK for a week, hope you will like this PR.
=> WIP: Improve WpfMath.Example layout

src/XamlMath.Shared/Boxes/HorizontalBox.cs
=> Simplify HorizontalBox.Add logic.

src/WpfMath.Tests/BoxTests.fs, src/WpfMath.Tests/TestResults/BoxTests.emptyMatrix.approved.txt, src/XamlMath.Shared/Atoms/MatrixAtom.cs
=> MatrixAtom: support empty rows

CHANGELOG.md, src/WpfMath.Tests/ParserExceptionTests.fs, src/WpfMath/Controls/FormulaControl.xaml.cs, src/XamlMath.Shared/TexFormulaParser.cs
=> (#272) Fix exception, improve exception reporting

src/XamlMath.Shared/TexPredefinedFormulaParser.cs
- Sealed the class (`TexPredefinedFormulaParser`) itself
- Fields with type `IDictionary<,>` never change (are only read, not written to) after the object is constructed, so I made them of type `IReadOnlyDictionary<,>`. All entry additions happen inside the constructor/s (I'm including the static constructor, as we will see in the next point).
- `typeMappings` and `argValueParsers` are always the same, in all instances, so I made them `static` and moved their construction to the static constructor. This can help us save on heap allocations.
- Sealed the `private` parser classes. Also, since most of them don't hold any internal state (and if the maintainer agrees) they can be turned into singletons in a future pull request.
- Nesting levels were decreased in the `Parse()` method through …
=> Refactored `TexPredefinedFormulaParser` to improve readability and ascertaining more invariants

src/XamlMath.Shared/Colors/HtmlColorParser.cs
I think it's more readable this way
=> Extracted calculations in `HtmlColorParser.ParseSingleComponent` into independent methods

api/AvaloniaMath.net462.verified.cs, api/AvaloniaMath.net6.0.verified.cs, api/AvaloniaMath.netstandard2.0.verified.cs, api/WpfMath.net462.verified.cs, api/WpfMath.net6.0.verified.cs, api/XamlMath.Shared.net462.verified.cs, api/XamlMath.Shared.net6.0.verified.cs, api/XamlMath.Shared.netstandard2.0.verified.cs, src/AvaloniaMath/Fonts/AvaloniaMathFontProvider.cs, src/AvaloniaMath/Rendering/AvaloniaBrush.cs, src/WpfMath/Fonts/WpfMathFontProvider.cs, src/WpfMath/Rendering/WpfBrush.cs, src/XamlMath.Shared/Colors/PredefinedColorParser.cs, src/XamlMath.Shared/Parsers/Matrices/MatrixCommandParser.cs, src/XamlMath.Shared/Parsers/StandardCommands.cs
And I know that I formally broke API compatibility again :) but there's no way to inherit from these classes if the constructor is `private`
=> Sealed classes that _only_ have `private` constructor/s

src/WpfMath/Rendering/GeometryElementRenderer.cs
Now you can apply a single transformation _or_ multiple transformations
=> Extracted method in `GeometryElementRenderer`

src/WpfMath/Controls/FormulaControl.xaml.cs, src/WpfMath/Controls/VisualContainerElement.cs
and removed unused namespace references, too
=> File-scoped namespace for `VisualContainerElement`

src/WpfMath/Controls/FormulaControl.xaml.cs
This already helps us decrease some nesting levels (see `ProcessBox()` method), but it should get a lot better after several refactorings
=> Extracted box processing method in `FormulaControl`

src/XamlMath.Shared/TexPredefinedFormulaSettingsParser.cs
The ugly `AddToMap()` method was removed and it was replaced with a generative approach
=> In `TexPredefinedFormulaSettingsParser`, methods `GetSymbolMappings` and `GetDelimiterMappings` were refactored and they now share the same mechanism.

XamlMath.All.sln, api/AvaloniaMath.net462.verified.cs, api/AvaloniaMath.net6.0.verified.cs, api/AvaloniaMath.netstandard2.0.verified.cs, api/ExcludedAttributes.txt, api/WpfMath.net462.verified.cs, api/WpfMath.net6.0.verified.cs, api/XamlMath.Shared.net462.verified.cs, api/XamlMath.Shared.net6.0.verified.cs, api/XamlMath.Shared.netstandard2.0.verified.cs, src/AvaloniaMath.ApiTest/AvaloniaMath.ApiTest.csproj, src/WpfMath.ApiTest/WpfMath.ApiTest.csproj
=> Tests: exclude compiler-generated attributes from the API files

src/WpfMath/Fonts/WpfSystemFont.cs, src/XamlMath.Shared/Boxes/CharBox.cs, src/XamlMath.Shared/DefaultTexFont.cs, src/XamlMath.Shared/DefaultTexFontParser.cs
=> Fixed #412

Directory.Build.props, XamlMath.All.sln, src/AvaloniaMath.ApiTest/ApiDefinitionTests.cs, src/AvaloniaMath.ApiTest/AvaloniaMath.ApiTest.csproj, src/XamlMath.ApiTest.Framework/ApiDefinitionsTestBase.cs, src/XamlMath.ApiTest.Framework/XamlMath.ApiTest.Framework.csproj, src/XamlMath.Shared.ApiTest/ApiDefinitionTests.cs, src/XamlMath.Shared.ApiTest/Usings.cs, src/XamlMath.Shared.ApiTest/XamlMath.Shared.ApiTest.csproj
=> (#481) Test: extract the shared API tests to a separate project

src/XamlMath.Shared/TexFormulaParser.cs
These methods were moved to the bottom of the file to keep track of them
This is a step towards what was discussed in #442
=> A few methods in `TexFormulaParser` were modified so that they return the updated positions instead of mutating them
