ForNeVeR/xaml-math

- WpfMath/Data/PredefinedTexFormulas.xml
- WpfMath/PredefinedTexFormulasParser.cs
- WpfMath/TexFormulaParser.cs
Thanks to Marc Palmans.
[Rendering of accent symbols](https://bugs.launchpad.net/wpf-math/+bug/1033830)
> Accent symbols are rendered separately instead of above other characters.
> The following patch appears to fix this issue but someone with more knowledge of the source code and latex should check it.
[Loading of predefined formulas](https://bugs.launchpad.net/wpf-math/+bug/1052586)
> I fixed some issues regarding the loading of predefinedformulas.xml Everything should work except \left and \right, but I think we should use TexFormulaHelper.AddEmbraced to do this. I've temporarily disabled those in the xml file.
before patches
after patches
#3
> Apply patches Rendering of accent symbols and Loading of predefined formulas

- WpfMath.Example/MainWindow.xaml
- WpfMath.Example/MainWindow.xaml.cs
- WpfMath/Box.cs
- WpfMath/CharBox.cs
- WpfMath/HorizontalBox.cs
- WpfMath/HorizontalRule.cs
- WpfMath/OverUnderBox.cs
- WpfMath/SVGConverter.cs
- WpfMath/TexRenderer.cs
- WpfMath/VerticalBox.cs
- WpfMath/WpfMath.csproj
Kudos to Marc Palmans!
[Feature: Render geometry & output as SVG](https://bugs.launchpad.net/wpf-math/+bug/1050955)
> I've added code to render to a Geometry and then convert it to an SVG snippet which then can be inserted in an SVG document. At the moment it's hard coded to black with no stroke as I don't need anything else. It should be very easy to add those features if you need them.
render in Inkscape
[svg-example.zip](https://github.com/ForNeVeR/wpf-math/files/768608/svg-example.zip)
#3
> Apply patch Feature: Render geometry & output as SVG

- WpfMath/Data/DefaultTexFont.xml
- WpfMath/Data/PredefinedTexFormulas.xml
- WpfMath/Data/TexSymbols.xml
- WpfMath/PredefinedTexFormulasParser.cs
- WpfMath/TexFormulaParser.cs
- WpfMath/WpfMath.csproj
Kudos to Marc Palmans.
[Added whitespace and % rendering](https://bugs.launchpad.net/wpf-math/+bug/1052891)
> I've added the whitespace commands \thinspace & short form \, and the other variants. I've also added the option to render \%
#3
> Apply patch Added whitespace and % rendering

- WpfMath.Example/MainWindow.xaml.cs
- WpfMath/Box.cs
- WpfMath/CharBox.cs
- WpfMath/HorizontalBox.cs
- WpfMath/ScriptsAtom.cs
- WpfMath/TexRenderer.cs
Kudos to Marc Palmans!
[Image size: Italic support](https://bugs.launchpad.net/wpf-math/+bug/1046669)
> Image size is incorrectly calculated when using italic.
> I'm not sure if this patch 100% correct but it seems to work for the samples I tested.
[incorrect image size when using subscript](https://bugs.launchpad.net/wpf-math/+bug/1041219)
> The bitmap size is calculated incorrectly when using subscript.
a_{b_{c_d}} before
a_{b_{c_d}} after
some \\, text \\, P before
some \\, text \\, P after
#3
> Apply patches Image size: Italic support and Incorrect image size when using subscript

- WpfMath.Example/MainWindow.xaml.cs
- WpfMath.Tests/ParserTests.fs
- WpfMath.Tests/Utils.fs
- WpfMath.sln
- WpfMath/Data/PredefinedTexFormulas.xml
- WpfMath/DelimiterInfo.cs
- WpfMath/TexFormulaParser.cs
- WpfMath/WpfMath.csproj
I've added the support for some of the delimiter types mentioned in #14.
Fortunately, it turned out that the render already supports this feature.  Here's the screenshot (check the big braces inside of the sum operator):
Remaining issues:
- `\left.` and `\right.` aren't supported (tracked in #14)
- parser is a mess of passed `ref` parameters (tracked in #29)
The implementation is yet very ad-hoc and maybe is missing very much important details; we'll need to determine and fix these later.
> Simple delimiter support

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath.Tests/Utils.fs
- src/WpfMath/Data/PredefinedTexFormulas.xml
- src/WpfMath/TexFormulaHelper.cs
- src/WpfMath/TexFormulaParser.cs
> Mathematical functions

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath.Tests/Utils.fs
- src/WpfMath/TexFormulaParser.cs
> Operators-symbols should be parsed as BigOp

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath/TexFormulaParser.cs
Example: "{}"
Expected: nothing to render
Actual: crash with NRE
> Fix crash while parsing empty groups

- WpfMath.sln
- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath/TexFormulaParser.cs
After report by @alexreg in #14 that `|` doesn't work I decided to review the delimiter typing. I've found that things like `\left)` are actually supposed to work, so I removed the constraint on the delimiter type from the closing brace code.
That way, now things like `\left| \frac{2}{2} \right|` work, and even `\left) \frac{2}{2} \right|`.
> Remove delimiter type constraint

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath.Tests/Utils.fs
- src/WpfMath/Data/TexFormulaSettings.xml
- src/WpfMath/Data/TexSymbols.xml
- src/WpfMath/FencedAtom.cs
- src/WpfMath/SymbolAtom.cs
- src/WpfMath/TexFormulaHelper.cs
- src/WpfMath/TexFormulaParser.cs
That's the last piece of #14. It allows to do things like this:
~~We already support rendering of `FencedAtom` with either `LeftDelimiter` or `RightDelimiter` being defined as `null`, so I've decided that we should construct it so when any delimiter is omitted.~~
~~Although our parser isn't `null`-tolerant at all, and I don't think it should be. So, parser generates symbols with a special names, and those get replaced when constructing the `FencedAtom`.~~
I've used another solution without abusing `null` values.
Closes #14.
> Support for empty delimiters

- README.md
That's the last missing piece of information about the font licensing.
Closes #66.
> #66: add information about Knuth license

- src/WpfMath/HorizontalBox.cs
- src/WpfMath/VerticalBox.cs
Fixes #50.
That's my another try to fix that long-standing issue. That time I've finally read the documentation (thanks @Atomosk for pointing me to the tutorial page [Draw lines excactly on physical device pixels](https://wpftutorial.net/DrawOnPhysicalDevicePixels.html)).
That time, we have no obvious regressions for any of the scale settings, so I think that's definitely a way to go. Check the comparison (_clickable_):
(The fonts are notably clearer now, and even without turning off the font antialiasing settings!)
These changes supersedes the changes in #52 and in the branches `bugfix/50-blur` and `bugfix/50-blur-alternate`; gonna to delete them after the merge.
> Use guidelines for WPF render

- WpfMath.sln
- src/WpfMath/Box.cs
- src/WpfMath/CharBox.cs
- src/WpfMath/HorizontalBox.cs
- src/WpfMath/OverUnderBox.cs
- src/WpfMath/TexRenderer.cs
- src/WpfMath/VerticalBox.cs
That's a follow-up for #71. I've decided to abstract the guidelines code from the `Draw` method, and implement the [Template method pattern](https://en.wikipedia.org/wiki/Template_method_pattern) (with `DrawWithGuidelines` being the template method and `Draw` being the primitive) for the following purposes:
- keep `Draw` clean from the guidelines code
- regain principial compatibility with #69 
- remove the need to call `base.Draw` in `Box`-derived classes
Now every box uses `DrawBackground` method and every box supports guidelines (my previous implementation worked only for `HorizontalBox` and `VerticalBox`).
> TexRenderer: abstract guidelines from drawing code

- src/WpfMath/CharBox.cs
- src/WpfMath/SVGConverter.cs
Second attempt.. *grin*
Feel free to criticize & correct.
I'm not a fan of the if(.. is polywhatever) and then .. as polywhatever. constructs (casting twice)
Not sure how to fix it while maintaining readability.
I was also thinking about ditching the entire RenderGeometry thing. It creates more problems than it solves. For example I wanted to include colors in the svg but the geometry only provides path data not colors.
edit: I forgot: currently the geometry returned by BuildGeometry auto converts to cubic bezier curves while truetype fonts has quadratic curves. I've added the case for quadratic curves but it's untested. Should you want to use a more general portable non-wpf (freetype, for example) method of reading/rendering fonts, it's already in there and should work.
> SVG: Added support for curves and removed flattening of the geometry

- src/WpfMath.Tests/BoxTests.fs
- src/WpfMath.Tests/ParserTests.fs
It turned out I was defining test functions as `internal` (the default for in-class `let` bindings in F#).
While generally working, this approach causes some tooling issues, so I've finally decided to fix that.
_(Also there was unnoticed function name duplication: see `\mathcal should be parsed properly`.)_
> Tests: make test functions public

- src/WpfMath/TexFormulaParser.cs
\sqrt{} resulted in a CTD. This should fix it.
> Fixed crash on empty square root

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath/TexFormulaParser.cs
The ReadScript method is checking for position length before potentially incrementing it with SkipWhiteSpace, leading to index out of bounds exception if you insert a whitespace after a _ or ^. Moving SkipWhiteSpace before the length check seems to fix the issue.
> Fixed a crash if inserting a whitespace after a _ or ^ symbol.

- src/WpfMath.Tests/CharBoxTests.fs
- src/WpfMath/TexFontInfo.cs
This fixes a crash when inputting characters or symbols not supported by the font. The issue was discovered using norwegian letters "æ, ø or å".
> Fixed a crash when rendering unsupported characters like "Å".

- README.md
- docs/prepare-font.md
I finally was able to generate most of the XML data from our font files. There're still some strange contradictions, but at least now they're documented!
Next step: #107.
Closes #70.
> Dealing with XML

- .gitignore
- src/WpfMath.Tests/BoxTests.fs
- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath/DefaultTexFont.cs
- src/WpfMath/ITeXFont.cs
- src/WpfMath/RowAtom.cs
- src/WpfMath/SystemFont.cs
- src/WpfMath/TexFormula.cs
- src/WpfMath/TexFormulaParser.cs
It turned out that the problem lies in the fact that WPF-Math tries to use `SymbolAtom`s in context of `\text` environment. `SymbolAtom` is tied to `TeXFont` and can't be used with `SystemFont`, so I decided to always use `CharAtom`s inside of `\text`.
- makes `CharAtom`s instead of `SymbolAtom`s inside `\text`
- marks `SystemFont` as not supporting the font metrics at the moment (so we won't try to query them in `RowAtom`)
- closes #104
> Fix rendering for stuff like \text{æ,}

- src/WpfMath.Tests/BoxTests.fs
- src/WpfMath/ScriptsAtom.cs
I've found that `ScriptsAtom` usually returns a shifted `CharAtom` (e.g. a `CharAtom` whose `Shift` is set), but in case when both `SubscriptAtom` and `SuperscriptAtom` are `null`, it returns essentially just a `new CharAtom` without the `Shift`. It causes bugs such as #119. I've decided to make `ScriptsAtom` always return the same kind of `CharAtoms` (i.e. the shifted ones).
Closes #119.
> Fix Shift of ScriptsAtom without any scripts

- src/WpfMath.Tests/DefaultTexFontTests.fs
- src/WpfMath.Tests/WpfMath.Tests.fsproj
- src/WpfMath/DefaultTexFont.cs
This is a preparation for #130.
> Add tests for DefaultTexFont, fix errors

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath.Tests/Utils.fs
- src/WpfMath/TexFormulaParser.cs
Added the functionality of command arguments being passed without braces. Such as "\infty" in \int_3^\infty, \frac17 and \sqrt\beta.
Closes #60.
TODO (by @ForNeVeR):
> #60 simplified command arguments

- src/WpfMath.Example/MainWindow.xaml.cs
- src/WpfMath.Tests/TexRendererTests.fs
- src/WpfMath.Tests/WpfMath.Tests.fsproj
- src/WpfMath/TexRenderer.cs
Closes #168.
I've added an additional method to render a bitmap with DPI (while keeping an old overload for binary compatibility), and fixed a couple of bugs noted in #168.
**Note for review:** please make sure to disable whitespace comparison. I've converted the line endings to `\n` (the standard we use) in a couple of files.
_This happens automatically whenever I commit anything and I think that's a good thing and we don't need to bother about it._
> Bitmap revolution

- src/WpfMath/TexFormulaParser.cs
In certain situations, the Source of scriptsAtom is null, like on {\hat T}. This causes the nullreference exception. I'm not clear on wheter it's supposed to be able to null or not, but i believe "position - initialPosition" should always be equal to the source length anyway.
> Fixed a crash due to Atom source being null when reading source length.

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath/Data/DefaultTexFont.xml
- src/WpfMath/Data/TexFormulaSettings.xml
- src/WpfMath/Data/TexSymbols.xml
- src/WpfMath/TexEnums.cs
- src/WpfMath/TexFormulaHelper.cs
- src/WpfMath/TexFormulaParser.cs
Closes #171.
The first commit was cherry-picked from [the commit](https://github.com/Altaxo/Altaxo/commit/60f8ca7b2da9ea057ad4a129ea707f3f31a3746a) [pointed](https://github.com/ForNeVeR/wpf-math/issues/171#issuecomment-449133395) by @lellid.
@lellid, thank you!
**TODO**:
- _confirmed, the changes are from CRLF to LF, so that's okay_
> Fix \lbrack and \rbrack

- src/WpfMath.Example/WpfMath.Example.csproj
- src/WpfMath.Tests/WpfMath.Tests.fsproj
- src/WpfMath/WpfMath.csproj
Otherwise, the code becomes harder to debug on .NET Framework (and we for now only support .NET Framework).
> Set DebugType to Full to prevent losing stack traces on .NET Framework

- appveyor.yml
- src/WpfMath.Example/WpfMath.Example.csproj
- src/WpfMath/WpfMath.csproj
This PR closes #193.
I had to [publish an update](https://github.com/SunburstApps/MSBuildSdks/compare/master...ForNeVeR:Sunburst.NET.Sdk.WindowsForms.Patched-v1.0.49) for the custom SDK we use to build WPF stuff with the .NET Core build system.
> VS2019 build compatibility

- src/WpfMath.Tests/WpfMath.Tests.fsproj
Otherwise they were failing on full PDBs, but we need those for Approvals.NET.
> Turn off the deterministic builds for F#

- src/WpfMath.Example/WpfMath.Example.csproj
- src/WpfMath/WpfMath.csproj
Closes #198.
This will allow me to use `IReadOnlyDictionary` where I need to (e.g. useful for #157).
Note that the unit test project have to use .NET 4.6.1 because of the test libraries we use. I wouldn't consider that as an issue though.
> Migrate to .NET 4.5.2

- src/WpfMath.Tests/ParserExceptionTests.fs
- src/WpfMath/Parsers/CommandParsers.cs
- src/WpfMath/Parsers/StandardCommands.cs
- src/WpfMath/TexFormulaParser.cs
This is a first step towards #157. It introduces an ability to pass a command parser collection into a `TexFormulaParser` constructor (this mechanism is unused yet, but will be used in #155 soon), and, as an excercise, ports one of our command parsers to the new system.
Other parsers will be ported later in #157. I don't expect anything extraordinary there, but we'll probably be able to share more parts of the parser implementations, and thus remove some code from the `TexFormulaParser`.
Tests will help to make sure there's absolutely no observable difference between the old and the new parser code.
> Initial implementation of parser extensions

- src/WpfMath.Tests/BoxTests.fs
- src/WpfMath.Tests/ParserExceptionTests.fs
- src/WpfMath.Tests/TestResults/BoxTests.emptyCommandText.approved.txt
- src/WpfMath.Tests/TestResults/BoxTests.emptyMathrm.approved.txt
- src/WpfMath/TexFormula.cs
- src/WpfMath/TexFormulaParser.cs
Change state "\mathrm{} should throw exn" to "\mathrm{} shouldn't throw exn"
> `\mathrm{}` shouldn't throw exn

- src/WpfMath.Tests/WpfMath.Tests.fsproj
I've found that the FSharp.Core version is for some reason hardcoded in our current `.fsproj`, and it causes compilation troubles in VS.
FSharp.Core is implicitly added by SDK anyways, so I see no reason to keep this reference inplace.
Closes #210.
> Delete FSharp.Core from the project file (#210)

- src/WpfMath/TexFontInfo.cs
The issue with this comment was noticed by @rstm-sf in #242.
This method never returns `null` (or `Result.Ok(null)`) and will return a `Result.Error` instead. I don't think that the comment without a remark about `null` holds any actual value, so I've decided to remove it completely.
> Remove a misleading comment

- src/WpfMath.Tests/CharBoxTests.fs
- src/WpfMath/Boxes/CharBox.cs
> Fix throw exception by \text{∅}

- src/WpfMath/Data/DefaultTexFont.xml
- src/WpfMath/Data/TexSymbols.xml
Added support for \\{ and \\} in addition to the existing \lbrace and \rbrace. These commands are in standard latex, but was missing here, making it incompatible.
> added support for \{ and \}

- src/WpfMath.Tests/TexRendererTests.fs
- src/WpfMath/TexRenderer.cs
The RenderToBitmap(double x, double y) method only adds padding to the left and top side of the bitmap. This fix adds padding to bottom and right as well. Perhaps there should be a Thickness as input instead though? It would make more sense but is a breaking change.
> Added equal padding to all sides when saving to bitmap

- .gitignore
Two items are getting removed:
- `/packages/` were added in ye olde times, and are only relevant for the old project system.
- `*.DotSettings` is ReSharper/Rider's way of sharing the settings (while any non-shared settings get written into `*.DotSettings.user`), so it shouldn't generally be ignored.
> .gitignore cleanup

- src/WpfMath.Example/MainWindow.xaml
- src/WpfMath/Controls/FormulaControl.xaml.cs
Hello!
Fix typo in `SystemTextFontNameProperty`
```
InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Double'.
This exception was originally thrown at this call stack:
WpfMath.Controls.FormulaControl.CoerceScaleValue(System.Windows.DependencyObject, object) in FormulaControl.xaml.cs
System.Windows.DependencyObject.ProcessCoerceValue(System.Windows.DependencyProperty, System.Windows.PropertyMetadata, ref System.Windows.EntryIndex, ref int, ref System.Windows.EffectiveValueEntry, ref System.Windows.EffectiveValueEntry, ref object, object, object, System.Windows.CoerceValueCallback, bool, bool, bool)
System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, …
```
> Fix typo in SystemTextFontNameProperty

- src/WpfMath/Boxes/CharBox.cs
- src/WpfMath/SystemFont.cs
Basically the new APIs require one to be explicit about pixels per DIP, which probably helps with high-DPI settings. This patch just gets rid of the warnings in a minimal way, while hopefully retaining the same functionality. It looks identical to me right now in both .NET 4 and .NET Core 3.1. I haven't yet tested with different DPI settings, though.
Intends to fix #232.
> Fixed warnings about obsolete WPF API in .NET Core.

- src/WpfMath.Tests/ParserTests.fs
- src/WpfMath.Tests/TestResults/ParserTests.limsup.approved.txt
- src/WpfMath/Parsers/PredefinedFormulae/PredefinedFormulaContext.cs
- src/WpfMath/TexPredefinedFormulaParser.cs
Closes #244, obsoletes #245 (and incorporates a test from it, for that matter).
This is a terminal fix for all the `TexPredefinedFormulas.xml` we were having earlier. I think I was already explaining this solution somewhere in my PR comments, but I've lost that comment since then. So, I had to reinvent this solution again!
> Fix predefined formula context sharing

- src/WpfMath/Controls/FormulaControl.xaml.cs
- src/WpfMath/TexEnvironment.cs
- src/WpfMath/TexFormula.cs
Closes #99. Obsoletes #162.
I've decided not to keep the binary compatibility with `TexFormula.GetRenderer` signature, since we're still technically in `0.*` version range.
> Support setting foreground and background via WPF control properties

- .gitattributes
Without this change, files get weirdly mangled on checking them out, `git rebase` and whatnot.
Initially, I got this version of `.gitattributes` from [this comment](https://github.com/actions/checkout/issues/135#issuecomment-613361104) on GitHub `checkout` Action repository.
Why have I even introduced this? Because I've decided we want to keep the line endings as `\n` (otherwise, they themselves get occasionally messed up by myself and other contributors). And then I found that GitHub Actions check out the repository with `autocrlf=true` on Windows. To avoid that, I wanted to do an equivalent of `core.autocrlf=input`, and took the advice from the aforementioned comment.
I was wrong, and I hope the problem gets fixed by this.
> .gitattributes: text=auto

- .github/workflows/main.yml
- .github/workflows/nuget.yml
Fixes partially: https://github.com/ForNeVeR/wpf-math/issues/298
What's new:
- Step `Read changelog` uses `ForNeVeR/ChangelogAutomation.action@v1`
- Versions bump for `checkout`, `cache`, `setup-dotnet`
- Added `workflow_dispatch` trigger
PS, I am not able to test nuget push due to security precautions of Github, however, output of read change log file is there: https://github.com/kolosovpetro/wpf-math/actions/runs/4018962182/jobs/6905216105#step:8:11
> Read changelog uses ForNeVeR/ChangelogAutomation.action@v1

- CHANGELOG.md
- api/XamlMath.Shared.net462.verified.cs
- api/XamlMath.Shared.net6.0.verified.cs
- api/XamlMath.Shared.netstandard2.0.verified.cs
- docs/environments.md
- src/WpfMath.Tests/EnvironmentTests.fs
- src/WpfMath.Tests/TestResults/EnvironmentTests.alignEnvironment.approved.txt
- src/WpfMath.Tests/TestResults/EnvironmentTests.alignEnvironmentLarge.approved.txt
- src/XamlMath.Shared/Atoms/MatrixAtom.cs
- src/XamlMath.Shared/Parsers/Matrices/MatrixCommandParser.cs
- src/XamlMath.Shared/Parsers/StandardCommands.cs
- src/XamlMath.Shared/TexEnums.cs
> Add \begin{align} support.

- src/AvaloniaMath/AvaloniaMath.csproj
- src/WpfMath/WpfMath.csproj
We are still going to state Knuth-CTAN in the documentation, but there's no way to tell this in NuGet metadata, unfortunately.
> Packaging: remove unsupported license expressions

- CHANGELOG.md
- api/WpfMath.net462.verified.cs
- api/WpfMath.net6.0.verified.cs
- api/XamlMath.Shared.net462.verified.cs
- api/XamlMath.Shared.net6.0.verified.cs
- api/XamlMath.Shared.netstandard2.0.verified.cs
- src/XamlMath.Shared/Exceptions/TexCharacterMappingNotFoundException.cs
- src/XamlMath.Shared/Exceptions/TexException.cs
- src/XamlMath.Shared/Exceptions/TexNotSupportedException.cs
- src/XamlMath.Shared/Exceptions/TexParseException.cs
- src/XamlMath.Shared/Exceptions/TextStyleMappingNotFoundException.cs
- src/XamlMath.Shared/Exceptions/TypeFaceNotFoundException.cs
Also, modernized namespace references (they are now file-scoped).
P.S. I don't know what is causing the build errors. Does sealing exception classes do anything that may cause them?
> Sealed exception types in `XamlMath.Shared\Exceptions`

- src/WpfMath/Controls/FormulaControl.xaml.cs
- src/XamlMath.Shared/Atoms/RowAtom.cs
- src/XamlMath.Shared/Atoms/SpaceAtom.cs
- src/XamlMath.Shared/Atoms/SymbolAtom.cs
- src/XamlMath.Shared/Boxes/Box.cs
- src/XamlMath.Shared/DefaultTexFontParser.cs
- src/XamlMath.Shared/GlueSettingsParser.cs
- src/XamlMath.Shared/TexPredefinedFormulaSettingsParser.cs
- src/XamlMath.Shared/TexSymbolParser.cs
Done automatically by IDE, but occurrences were few, so reviewing it shouldn't be too daunting
> Private fields which are never modified were made `readonly`

- src/WpfMath/Converters/SVGConverter.cs
Specifically, these `if` towers were for pattern matching
Also, started using file-scoped namespace
> `SVGConverter.cs`: converted `if` towers to `switch` statements

- src/XamlMath.Shared/Atoms/SymbolAtom.cs
- src/XamlMath.Shared/Glue.cs
- src/XamlMath.Shared/GlueSettingsParser.cs
- src/XamlMath.Shared/TexFontInfo.cs
- src/XamlMath.Shared/TexFormulaParser.cs
- src/XamlMath.Shared/TexPredefinedFormulaParser.cs
- src/XamlMath.Shared/TexPredefinedFormulaSettingsParser.cs
- src/XamlMath.Shared/TexSymbolParser.cs
This is a nudge towards immutability, which gives us greater piece of mind when coding.
In `XamlMath.Shared` there are methods that create mappings and lists to be looked up. These methods usually return arrays or lists that expose the `IList<T>` interface.
Where possible, the methods were made to return `IReadOnlyList<T>` or `IEnumerable<T>` instead. This makes their intent clearer (they are not to be modified, just used for lookup).
Similarly, some methods that return `IDictionary<TKey,TValue>` were made to return `IReadOnlyDictionary<TKey,TValue>`.
The types of the fields that store these lists or mappings were changed accordingly.
`internal` classes involved were `sealed`.
No changes to the public API.
> Internal refactoring - little nudge towards immutable code

- src/XamlMath.Shared/TexFormulaParser.cs
I see that this parser is mutation-based...In the future I'd like to make it more immutable, more functional, and more generation-based. This is a step in that direction (although I don't think that's obvious right now). Thankfully all methods are private so refactoring is easier
> Extracted method for parsing left group char in `TexFormulaParser`

- CHANGELOG.md
- api/AvaloniaMath.net462.verified.cs
- api/AvaloniaMath.net6.0.verified.cs
- api/AvaloniaMath.netstandard2.0.verified.cs
- src/AvaloniaMath/Fonts/AvaloniaMathFontProvider.cs
- src/WpfMath/Fonts/WpfMathFontProvider.cs
I know that this formally breaks the API, but it doesn't make sense to re-assign those static fields, and also they don't have any internal state, so nothing should break
> Made singleton `Instance`s `readonly`

- api/XamlMath.Shared.net462.verified.cs
- api/XamlMath.Shared.net6.0.verified.cs
- api/XamlMath.Shared.netstandard2.0.verified.cs
- src/XamlMath.Shared/DelimiterMappingNotFoundException.cs
- src/XamlMath.Shared/FormulaNotFoundException.cs
- src/XamlMath.Shared/SymbolMappingNotFoundException.cs
- src/XamlMath.Shared/SymbolNotFoundException.cs
Also, in the particular case of these exceptions, not only does it not make sense to inherit from them, but their constructors are `internal`, so there already wasn't any way of inheriting from them
> Sealed more exception classes

- src/WpfMath/Converters/SVGConverter.cs
Also, I'm not sure why `m_nestedLevel` is needed, so I commented it out, but the code is still there if it's needed
> `WpfMath.Converters.SVGConverter` now enumerates resulting strings with `yield return` instead of adding to `StringBuilder`

- src/XamlMath.Shared/DefaultTexFont.cs
- src/XamlMath.Shared/DefaultTexFontParser.cs
They are never modified after their creation, but read-only interfaces make it clearer.
I also simplified some code in other ways, like removing unnecessary constructor bodies.
> Collections (arrays, dictionaries) used in `DefaultTextFont` and `DefaultTexFontParser` now use read-only interfaces

- src/WpfMath/Extensions.cs
- src/WpfMath/Fonts/WpfSystemFont.cs
- src/WpfMath/Rendering/WpfElementRenderer.cs
- src/XamlMath.Shared/Atoms/DummyAtom.cs
- src/XamlMath.Shared/Atoms/ScriptsAtom.cs
- src/XamlMath.Shared/Parsers/PredefinedFormulae/PredefinedFormulaContext.cs
- src/XamlMath.Shared/SourceSpan.cs
- src/XamlMath.Shared/Utils/Result.cs
The purpose is twofold: being more concise and reduce repetition.
Also, improved `null` checks in `Equals` methods of `SourceSpan`
> Shortened `new()` expressions in several places

- src/XamlMath.Shared/DefaultTexFontParser.cs
- src/XamlMath.Shared/DelimiterMappingNotFoundException.cs
- src/XamlMath.Shared/Exceptions/TextStyleMappingNotFoundException.cs
- src/XamlMath.Shared/FormulaNotFoundException.cs
- src/XamlMath.Shared/SymbolMappingNotFoundException.cs
- src/XamlMath.Shared/SymbolNotFoundException.cs
Also, removed unnecessary dictionary lookup in `DefaultTexFontParser.cs`, in `GetDefaultTextStyleMappings()`. Notice that the variable just below the one that was deleted accesses the exact same value.
> Converted `string.Format` to interpolated string

- src/WpfMath.Example/MainViewModel.cs
This helps us get rid of the awkward variable assignment inside the `try` block, and we can just assign the variable directly
> Inside `MainViewModel.Export()`, exception handling was made using a more specific exception type

- src/XamlMath.Shared/Atoms/FractionAtom.cs
I think the original method is long and chaotic. Hopefully this can help improve it, even if it's not yet perfect
> Extracted some logic from `FractionAtom.CreateBoxCore` into its own methods

- src/WpfMath.Example/MainViewModel.cs
- src/XamlMath.Shared/Atoms/BigOperatorAtom.cs
I think the original method is long and chaotic. Hopefully this can help improve it, even if it's not yet perfect
> Split `BigOperatorAtom.CreateBoxCore` into smaller methods

- src/XamlMath.Shared/Parsers/Matrices/MatrixCommandParser.cs
- src/XamlMath.Shared/Parsers/ProcessEnvironmentCommand.cs
- src/XamlMath.Shared/Parsers/StandardCommands.cs
- src/XamlMath.Shared/TexFormulaParser.cs
Similar to #489, but the number of changes is enough to need its own pull request.
The end goal is having the `TexFormulaParser` returning the new values instead of mutating the existing ones.
> `TexFormulaParser.ReadElement` was modified so that it returns the updated position instead of mutating it
